export default ITEMS = [
  {
    id: 1,
    name: '🌻 Seeds',
    description: 'For afternoon tea time',
    price: '$5.99',
    rating: 4.9,
    image: require('./assets/images/item-1.png'),
  },
  {
    id: 2,
    name: 'Taiyaki',
    description: 'Japanese ice cream',
    price: '$3.99',
    rating: 4.9,
    image: require('./assets/images/item-2.png'),
  },
  {
    id: 3,
    name: 'Simit lovers',
    description: '',
    price: '$15.99',
    rating: 4.9,
    image: require('./assets/images/item-3.png'),
  },
  {
    id: 4,
    name: 'Simit lovers',
    description: '',
    price: '$15.99',
    rating: 4.9,
    image: require('./assets/images/item-1.png'),
  },
  {
    id: 5,
    name: 'Simit lovers',
    description: '',
    price: '$100.99',
    rating: 4,
    image: require('./assets/images/item-2.png'),
  },
  {
    id: 6,
    name: '🌻 Seeds',
    description: 'For afternoon tea time',
    price: '$5.99',
    rating: 4.9,
    image: require('./assets/images/item-1.png'),
  },
  {
    id: 7,
    name: 'Taiyaki',
    description: 'Japanese ice cream',
    price: '$3.99',
    rating: 4.9,
    image: require('./assets/images/item-2.png'),
  },
  {
    id: 8,
    name: 'Simit lovers',
    description: '',
    price: '$15.99',
    rating: 4.9,
    image: require('./assets/images/item-3.png'),
  },
  {
    id: 9,
    name: 'Simit lovers',
    description: '',
    price: '$15.99',
    rating: 4.9,
    image: require('./assets/images/item-1.png'),
  },
  {
    id: 10,
    name: 'Simit lovers',
    description: '',
    price: '$100.99',
    rating: 4,
    image: require('./assets/images/item-2.png'),
  },
];
